
import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aluno.marumby
 */
public class Cartela extends javax.swing.JFrame {

    /**
     * Creates new form Cartela
     */
    public Cartela() {
        initComponents();
       // Cartela.setLocationRelativeTo(null);
    }

    int numCartela;
    int[] numSorteio = new int[60];
    int numLimite;
    static int Quantidade = 6;
    String nomeJogador;
    String jogoText = "";
    ArrayList<Integer> jogo = new ArrayList<Integer>();
    public static ArrayList<jogoMega> todosJogos = new ArrayList<jogoMega>();
    
     
    static boolean existeNumero(int[] numeros, int n){
        for (int i = 0; i < numeros.length; i++)
        {
            if (numeros[i] == n){
                return true;
            }
        }
        return false;
    }
    
    public static int[] sorteaSena(){
        int NUMERO_DEZENAS = 6;
        int[] resultado = new int[NUMERO_DEZENAS];
        for (int i = 0; i < NUMERO_DEZENAS; i++){
            boolean repetido = false;
            int sorteado;
            
            do {
                sorteado = 1 + (int)(Math.random()*60);
                repetido = existeNumero(resultado, sorteado);
            } while (repetido);
            
            resultado[i] = sorteado; 
        }
        return resultado;
    }
    
    public static int[] criaRandom(){
        int NUMERO_DEZENAS = Quantidade;
        int[] resultado = new int[NUMERO_DEZENAS];
        for (int i = 0; i < NUMERO_DEZENAS; i++){
            boolean repetido = false;
            int sorteado;
            
            do {
                sorteado = 1 + (int)(Math.random()*60);
                repetido = existeNumero(resultado, sorteado);
            } while (repetido);
            
            resultado[i] = sorteado; 
        }
        return resultado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Dz01 = new javax.swing.JCheckBox();
        Dz02 = new javax.swing.JCheckBox();
        Dz03 = new javax.swing.JCheckBox();
        Dz04 = new javax.swing.JCheckBox();
        Dz05 = new javax.swing.JCheckBox();
        Dz06 = new javax.swing.JCheckBox();
        Dz07 = new javax.swing.JCheckBox();
        Dz08 = new javax.swing.JCheckBox();
        Dz09 = new javax.swing.JCheckBox();
        Dz10 = new javax.swing.JCheckBox();
        Dz20 = new javax.swing.JCheckBox();
        Dz19 = new javax.swing.JCheckBox();
        Dz13 = new javax.swing.JCheckBox();
        Dz12 = new javax.swing.JCheckBox();
        Dz11 = new javax.swing.JCheckBox();
        Dz15 = new javax.swing.JCheckBox();
        Dz16 = new javax.swing.JCheckBox();
        Dz17 = new javax.swing.JCheckBox();
        Dz18 = new javax.swing.JCheckBox();
        Dz14 = new javax.swing.JCheckBox();
        Dz23 = new javax.swing.JCheckBox();
        Dz29 = new javax.swing.JCheckBox();
        Dz30 = new javax.swing.JCheckBox();
        Dz27 = new javax.swing.JCheckBox();
        Dz28 = new javax.swing.JCheckBox();
        Dz25 = new javax.swing.JCheckBox();
        Dz26 = new javax.swing.JCheckBox();
        Dz22 = new javax.swing.JCheckBox();
        Dz21 = new javax.swing.JCheckBox();
        Dz24 = new javax.swing.JCheckBox();
        Dz33 = new javax.swing.JCheckBox();
        Dz39 = new javax.swing.JCheckBox();
        Dz40 = new javax.swing.JCheckBox();
        Dz37 = new javax.swing.JCheckBox();
        Dz38 = new javax.swing.JCheckBox();
        Dz35 = new javax.swing.JCheckBox();
        Dz36 = new javax.swing.JCheckBox();
        Dz32 = new javax.swing.JCheckBox();
        Dz31 = new javax.swing.JCheckBox();
        Dz34 = new javax.swing.JCheckBox();
        Dz43 = new javax.swing.JCheckBox();
        Dz49 = new javax.swing.JCheckBox();
        Dz50 = new javax.swing.JCheckBox();
        Dz47 = new javax.swing.JCheckBox();
        Dz48 = new javax.swing.JCheckBox();
        Dz45 = new javax.swing.JCheckBox();
        Dz46 = new javax.swing.JCheckBox();
        Dz42 = new javax.swing.JCheckBox();
        Dz41 = new javax.swing.JCheckBox();
        Dz44 = new javax.swing.JCheckBox();
        Dz53 = new javax.swing.JCheckBox();
        Dz59 = new javax.swing.JCheckBox();
        Dz60 = new javax.swing.JCheckBox();
        Dz57 = new javax.swing.JCheckBox();
        Dz58 = new javax.swing.JCheckBox();
        Dz55 = new javax.swing.JCheckBox();
        Dz56 = new javax.swing.JCheckBox();
        Dz52 = new javax.swing.JCheckBox();
        Dz51 = new javax.swing.JCheckBox();
        Dz54 = new javax.swing.JCheckBox();
        salvarAposta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        aposta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CartelaNum = new javax.swing.JLabel();
        Random = new javax.swing.JButton();
        Sorteio = new javax.swing.JButton();
        Qnt6 = new javax.swing.JRadioButton();
        Qnt7 = new javax.swing.JRadioButton();
        Qnt8 = new javax.swing.JRadioButton();
        Qnt9 = new javax.swing.JRadioButton();
        Qnt10 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Dz01.setText("01");
        Dz01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz01ActionPerformed(evt);
            }
        });

        Dz02.setText("02");
        Dz02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz02ActionPerformed(evt);
            }
        });

        Dz03.setText("03");
        Dz03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz03ActionPerformed(evt);
            }
        });

        Dz04.setText("04");
        Dz04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz04ActionPerformed(evt);
            }
        });

        Dz05.setText("05");
        Dz05.setToolTipText("");
        Dz05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz05ActionPerformed(evt);
            }
        });

        Dz06.setText("06");
        Dz06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz06ActionPerformed(evt);
            }
        });

        Dz07.setText("07");
        Dz07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz07ActionPerformed(evt);
            }
        });

        Dz08.setText("08");
        Dz08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz08ActionPerformed(evt);
            }
        });

        Dz09.setText("09");
        Dz09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz09ActionPerformed(evt);
            }
        });

        Dz10.setText("10");
        Dz10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz10ActionPerformed(evt);
            }
        });

        Dz20.setText("20");
        Dz20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz20ActionPerformed(evt);
            }
        });

        Dz19.setText("19");
        Dz19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz19ActionPerformed(evt);
            }
        });

        Dz13.setText("13");
        Dz13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz13ActionPerformed(evt);
            }
        });

        Dz12.setText("12");
        Dz12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz12ActionPerformed(evt);
            }
        });

        Dz11.setText("11");
        Dz11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz11ActionPerformed(evt);
            }
        });

        Dz15.setText("15");
        Dz15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz15ActionPerformed(evt);
            }
        });

        Dz16.setText("16");
        Dz16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz16ActionPerformed(evt);
            }
        });

        Dz17.setText("17");
        Dz17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz17ActionPerformed(evt);
            }
        });

        Dz18.setText("18");
        Dz18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz18ActionPerformed(evt);
            }
        });

        Dz14.setText("14");
        Dz14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz14ActionPerformed(evt);
            }
        });

        Dz23.setText("23");
        Dz23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz23ActionPerformed(evt);
            }
        });

        Dz29.setText("29");
        Dz29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz29ActionPerformed(evt);
            }
        });

        Dz30.setText("30");
        Dz30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz30ActionPerformed(evt);
            }
        });

        Dz27.setText("27");
        Dz27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz27ActionPerformed(evt);
            }
        });

        Dz28.setText("28");
        Dz28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz28ActionPerformed(evt);
            }
        });

        Dz25.setText("25");
        Dz25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz25ActionPerformed(evt);
            }
        });

        Dz26.setText("26");
        Dz26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz26ActionPerformed(evt);
            }
        });

        Dz22.setText("22");
        Dz22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz22ActionPerformed(evt);
            }
        });

        Dz21.setText("21");
        Dz21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz21ActionPerformed(evt);
            }
        });

        Dz24.setText("24");
        Dz24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz24ActionPerformed(evt);
            }
        });

        Dz33.setText("33");
        Dz33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz33ActionPerformed(evt);
            }
        });

        Dz39.setText("39");
        Dz39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz39ActionPerformed(evt);
            }
        });

        Dz40.setText("40");
        Dz40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz40ActionPerformed(evt);
            }
        });

        Dz37.setText("37");
        Dz37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz37ActionPerformed(evt);
            }
        });

        Dz38.setText("38");
        Dz38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz38ActionPerformed(evt);
            }
        });

        Dz35.setText("35");
        Dz35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz35ActionPerformed(evt);
            }
        });

        Dz36.setText("36");
        Dz36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz36ActionPerformed(evt);
            }
        });

        Dz32.setText("32");
        Dz32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz32ActionPerformed(evt);
            }
        });

        Dz31.setText("31");
        Dz31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz31ActionPerformed(evt);
            }
        });

        Dz34.setText("34");
        Dz34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz34ActionPerformed(evt);
            }
        });

        Dz43.setText("43");
        Dz43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz43ActionPerformed(evt);
            }
        });

        Dz49.setText("49");
        Dz49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz49ActionPerformed(evt);
            }
        });

        Dz50.setText("50");
        Dz50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz50ActionPerformed(evt);
            }
        });

        Dz47.setText("47");
        Dz47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz47ActionPerformed(evt);
            }
        });

        Dz48.setText("48");
        Dz48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz48ActionPerformed(evt);
            }
        });

        Dz45.setText("45");
        Dz45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz45ActionPerformed(evt);
            }
        });

        Dz46.setText("46");
        Dz46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz46ActionPerformed(evt);
            }
        });

        Dz42.setText("42");
        Dz42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz42ActionPerformed(evt);
            }
        });

        Dz41.setText("41");
        Dz41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz41ActionPerformed(evt);
            }
        });

        Dz44.setText("44");
        Dz44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz44ActionPerformed(evt);
            }
        });

        Dz53.setText("53");
        Dz53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz53ActionPerformed(evt);
            }
        });

        Dz59.setText("59");
        Dz59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz59ActionPerformed(evt);
            }
        });

        Dz60.setText("60");
        Dz60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz60ActionPerformed(evt);
            }
        });

        Dz57.setText("57");
        Dz57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz57ActionPerformed(evt);
            }
        });

        Dz58.setText("58");
        Dz58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz58ActionPerformed(evt);
            }
        });

        Dz55.setText("55");
        Dz55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz55ActionPerformed(evt);
            }
        });

        Dz56.setText("56");
        Dz56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz56ActionPerformed(evt);
            }
        });

        Dz52.setText("52");
        Dz52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz52ActionPerformed(evt);
            }
        });

        Dz51.setText("51");
        Dz51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz51ActionPerformed(evt);
            }
        });

        Dz54.setText("54");
        Dz54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dz54ActionPerformed(evt);
            }
        });

        salvarAposta.setText("Salvar aposta");
        salvarAposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarApostaActionPerformed(evt);
            }
        });

        jLabel1.setText("Numeros:");

        jLabel4.setText("CARTELA:");

        CartelaNum.setText("0");

        Random.setText("RANDOM");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        Sorteio.setText("Sorteio");
        Sorteio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SorteioActionPerformed(evt);
            }
        });

        buttonGroup1.add(Qnt6);
        Qnt6.setSelected(true);
        Qnt6.setText("6");
        Qnt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qnt6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Qnt7);
        Qnt7.setText("7");
        Qnt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qnt7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Qnt8);
        Qnt8.setText("8");
        Qnt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qnt8ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Qnt9);
        Qnt9.setText("9");
        Qnt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qnt9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Qnt10);
        Qnt10.setText("10");
        Qnt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Qnt10ActionPerformed(evt);
            }
        });

        jLabel2.setText("QUANTIDADE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarAposta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sorteio))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dz11)
                                    .addComponent(Dz01))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dz02)
                                    .addComponent(Dz12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Dz13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dz14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Dz03)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dz04)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dz05)
                                    .addComponent(Dz15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dz06)
                                    .addComponent(Dz16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dz07)
                                    .addComponent(Dz17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Dz08)
                                    .addComponent(Dz18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Dz19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Dz20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Dz09)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Dz10))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dz41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dz42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz50))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dz31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dz32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz40))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dz21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dz22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Random)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aposta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dz51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dz52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dz60))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Qnt6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Qnt7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Qnt8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Qnt9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Qnt10))
                                    .addComponent(CartelaNum))))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Dz01, Dz02, Dz03, Dz04, Dz05, Dz06, Dz07, Dz08, Dz09, Dz10, Dz11, Dz12, Dz13, Dz14, Dz15, Dz16, Dz17, Dz18, Dz19, Dz20, Dz21, Dz22, Dz23, Dz24, Dz25, Dz26, Dz27, Dz28, Dz29, Dz30, Dz31, Dz32, Dz33, Dz34, Dz35, Dz36, Dz37, Dz38, Dz39, Dz40, Dz41, Dz42, Dz43, Dz44, Dz45, Dz46, Dz47, Dz48, Dz49, Dz50, Dz51, Dz52, Dz53, Dz54, Dz55, Dz56, Dz57, Dz58, Dz59, Dz60});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CartelaNum)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Qnt6)
                    .addComponent(Qnt7)
                    .addComponent(Qnt8)
                    .addComponent(Qnt9)
                    .addComponent(Qnt10)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dz01)
                            .addComponent(Dz02)
                            .addComponent(Dz03)
                            .addComponent(Dz04)
                            .addComponent(Dz05)
                            .addComponent(Dz06)
                            .addComponent(Dz07))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dz11)
                            .addComponent(Dz12)
                            .addComponent(Dz13)
                            .addComponent(Dz14)
                            .addComponent(Dz15)
                            .addComponent(Dz16)
                            .addComponent(Dz17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dz21)
                            .addComponent(Dz22)
                            .addComponent(Dz23)
                            .addComponent(Dz24)
                            .addComponent(Dz25)
                            .addComponent(Dz26)
                            .addComponent(Dz27)
                            .addComponent(Dz28)
                            .addComponent(Dz29)
                            .addComponent(Dz30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dz31)
                            .addComponent(Dz32)
                            .addComponent(Dz33)
                            .addComponent(Dz34)
                            .addComponent(Dz35)
                            .addComponent(Dz36)
                            .addComponent(Dz37)
                            .addComponent(Dz38)
                            .addComponent(Dz39)
                            .addComponent(Dz40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dz41)
                            .addComponent(Dz42)
                            .addComponent(Dz43)
                            .addComponent(Dz44)
                            .addComponent(Dz45)
                            .addComponent(Dz46)
                            .addComponent(Dz47)
                            .addComponent(Dz48)
                            .addComponent(Dz49)
                            .addComponent(Dz50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dz51)
                            .addComponent(Dz52)
                            .addComponent(Dz53)
                            .addComponent(Dz54)
                            .addComponent(Dz55)
                            .addComponent(Dz56)
                            .addComponent(Dz57)
                            .addComponent(Dz58)
                            .addComponent(Dz59)
                            .addComponent(Dz60))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(aposta)
                            .addComponent(Random)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dz08)
                            .addComponent(Dz09)
                            .addComponent(Dz10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dz18)
                            .addComponent(Dz19)
                            .addComponent(Dz20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarAposta)
                    .addComponent(Sorteio))
                .addGap(7, 7, 7))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Dz01, Dz02, Dz03, Dz04, Dz05, Dz06, Dz07, Dz08, Dz09, Dz10, Dz11, Dz12, Dz13, Dz14, Dz15, Dz16, Dz17, Dz18, Dz19, Dz20, Dz21, Dz22, Dz23, Dz24, Dz25, Dz26, Dz27, Dz28, Dz29, Dz30, Dz31, Dz32, Dz33, Dz34, Dz35, Dz36, Dz37, Dz38, Dz39, Dz40, Dz41, Dz42, Dz43, Dz44, Dz45, Dz46, Dz47, Dz48, Dz49, Dz50, Dz51, Dz52, Dz53, Dz54, Dz55, Dz56, Dz57, Dz58, Dz59, Dz60});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed

        int[] random = new int[Quantidade-1];
               random = criaRandom();
    
        jogo.clear();
               
        Dz01.setSelected(false);
        Dz02.setSelected(false);
        Dz03.setSelected(false);
        Dz04.setSelected(false);
        Dz05.setSelected(false);
        Dz06.setSelected(false);
        Dz07.setSelected(false);
        Dz08.setSelected(false);
        Dz09.setSelected(false);
        Dz10.setSelected(false);
        
        Dz11.setSelected(false);
        Dz12.setSelected(false);
        Dz13.setSelected(false);
        Dz14.setSelected(false);
        Dz15.setSelected(false);
        Dz16.setSelected(false);
        Dz17.setSelected(false);
        Dz18.setSelected(false);
        Dz19.setSelected(false);
        Dz20.setSelected(false);
        
        Dz21.setSelected(false);
        Dz22.setSelected(false);
        Dz23.setSelected(false);
        Dz24.setSelected(false);
        Dz25.setSelected(false);
        Dz26.setSelected(false);
        Dz27.setSelected(false);
        Dz28.setSelected(false);
        Dz29.setSelected(false);
        Dz30.setSelected(false);
        
        Dz31.setSelected(false);
        Dz32.setSelected(false);
        Dz33.setSelected(false);
        Dz34.setSelected(false);
        Dz35.setSelected(false);
        Dz36.setSelected(false);
        Dz37.setSelected(false);
        Dz38.setSelected(false);
        Dz39.setSelected(false);
        Dz40.setSelected(false);
        
        Dz41.setSelected(false);
        Dz42.setSelected(false);
        Dz43.setSelected(false);
        Dz44.setSelected(false);
        Dz45.setSelected(false);
        Dz46.setSelected(false);
        Dz47.setSelected(false);
        Dz48.setSelected(false);
        Dz49.setSelected(false);
        Dz50.setSelected(false);
        
        Dz51.setSelected(false);
        Dz52.setSelected(false);
        Dz53.setSelected(false);
        Dz54.setSelected(false);
        Dz55.setSelected(false);
        Dz56.setSelected(false);
        Dz57.setSelected(false);
        Dz58.setSelected(false);
        Dz59.setSelected(false);
        Dz60.setSelected(false);
        
        
        
        int i = 0;
        for  (i = 0; i <= random.length-1; i++){
            int escolha = random[i];
            switch (escolha){
                case 1:
                    Dz01.setSelected(true);
                    this.Dz01ActionPerformed(evt);
                    break;
                case 2:
                    Dz02.setSelected(true);
                    this.Dz02ActionPerformed(evt);
                    break;
                case 3:
                    Dz03.setSelected(true);
                    this.Dz03ActionPerformed(evt);
                    break;
                case 4:
                    Dz04.setSelected(true);
                    this.Dz04ActionPerformed(evt);
                    break;
                case 5:
                    Dz05.setSelected(true);
                    this.Dz05ActionPerformed(evt);
                    break;
                case 6:
                    Dz06.setSelected(true);
                    this.Dz06ActionPerformed(evt);
                    break;
                case 7:
                    Dz07.setSelected(true);
                    this.Dz07ActionPerformed(evt);
                    break;
                case 8:
                    Dz08.setSelected(true);
                    this.Dz08ActionPerformed(evt);
                    break;
                case 9:
                    Dz09.setSelected(true);
                    this.Dz09ActionPerformed(evt);
                    break;
                case 10:
                    Dz10.setSelected(true);
                    this.Dz10ActionPerformed(evt);
                    break;
                case 11:
                    Dz11.setSelected(true);
                    this.Dz11ActionPerformed(evt);
                    break;
                case 12:
                    Dz12.setSelected(true);
                    this.Dz12ActionPerformed(evt);
                    break;
                case 13:
                    Dz13.setSelected(true);
                    this.Dz13ActionPerformed(evt);
                    break;
                case 14:
                    Dz14.setSelected(true);
                    this.Dz14ActionPerformed(evt);
                    break;
                case 15:
                    Dz15.setSelected(true);
                    this.Dz15ActionPerformed(evt);
                    break;
                case 16:
                    Dz16.setSelected(true);
                    this.Dz16ActionPerformed(evt);
                    break;
                case 17:
                    Dz17.setSelected(true);
                    this.Dz17ActionPerformed(evt);
                    break;
                case 18:
                    Dz18.setSelected(true);
                    this.Dz18ActionPerformed(evt);
                    break;
                case 19:
                    Dz19.setSelected(true);
                    this.Dz19ActionPerformed(evt);
                    break;
                case 20:
                    Dz20.setSelected(true);
                    this.Dz20ActionPerformed(evt);
                    break;
                case 21:
                    Dz21.setSelected(true);
                     this.Dz21ActionPerformed(evt);
                    break;
                case 22:
                    Dz22.setSelected(true);
                     this.Dz22ActionPerformed(evt);
                    break;
                case 23:
                    Dz23.setSelected(true);
                    this.Dz23ActionPerformed(evt);
                    break;
                case 24:
                    Dz24.setSelected(true);
                     this.Dz24ActionPerformed(evt);
                    break;
                case 25:
                    Dz25.setSelected(true);
                     this.Dz25ActionPerformed(evt);
                    break;
                case 26:
                    Dz26.setSelected(true);
                     this.Dz26ActionPerformed(evt);
                    break;
                case 27:
                    Dz27.setSelected(true);
                     this.Dz27ActionPerformed(evt);
                    break;
                case 28:
                    Dz28.setSelected(true);
                     this.Dz28ActionPerformed(evt);
                    break;
                case 29:
                    Dz29.setSelected(true);
                     this.Dz29ActionPerformed(evt);
                    break;
                case 30:
                    Dz30.setSelected(true);
                     this.Dz30ActionPerformed(evt);
                    break;
                case 31:
                    Dz31.setSelected(true);
                    this.Dz31ActionPerformed(evt);
                    break;
                case 32:
                    Dz32.setSelected(true);
                    this.Dz32ActionPerformed(evt);
                    break;
                case 33:
                    Dz33.setSelected(true);
                    this.Dz33ActionPerformed(evt);
                    break;
                case 34:
                    Dz34.setSelected(true);
                    this.Dz34ActionPerformed(evt);
                    break;
                case 35:
                    Dz35.setSelected(true);
                    this.Dz35ActionPerformed(evt);
                    break;
                case 36:
                    Dz36.setSelected(true);
                    this.Dz36ActionPerformed(evt);
                    break;
                case 37:
                    Dz37.setSelected(true);
                    this.Dz37ActionPerformed(evt);
                    break;
                case 38:
                    Dz38.setSelected(true);
                    this.Dz38ActionPerformed(evt);
                    break;
                case 39:
                    Dz39.setSelected(true);
                    this.Dz39ActionPerformed(evt);
                    break;
                case 40:
                    Dz40.setSelected(true);
                    this.Dz40ActionPerformed(evt);
                    break;
                case 41:
                    Dz41.setSelected(true);
                    this.Dz41ActionPerformed(evt);
                    break;
                case 42:
                    Dz42.setSelected(true);
                    this.Dz42ActionPerformed(evt);
                    break;
                case 43:
                    Dz43.setSelected(true);
                    this.Dz43ActionPerformed(evt);
                    break;
                case 44:
                    Dz44.setSelected(true);
                    this.Dz44ActionPerformed(evt);
                    break;
                case 45:
                    Dz45.setSelected(true);
                    this.Dz45ActionPerformed(evt);
                    break;
                case 46:
                    Dz46.setSelected(true);
                    this.Dz46ActionPerformed(evt);
                    break;
                case 47:
                    Dz47.setSelected(true);
                    this.Dz47ActionPerformed(evt);
                    break;
                case 48:
                    Dz48.setSelected(true);
                    this.Dz48ActionPerformed(evt);
                    break;
                case 49:
                    Dz49.setSelected(true);
                    this.Dz49ActionPerformed(evt);
                    break;
                case 50:
                    Dz50.setSelected(true);
                    this.Dz50ActionPerformed(evt);
                    break;
                case 51:
                    Dz51.setSelected(true);
                    this.Dz51ActionPerformed(evt);
                    break;
                case 52:
                    Dz52.setSelected(true);
                    this.Dz52ActionPerformed(evt);
                    break;
                case 53:
                    Dz53.setSelected(true);
                    this.Dz53ActionPerformed(evt);
                    break;
                case 54:
                    Dz54.setSelected(true);
                    this.Dz54ActionPerformed(evt);
                    break;
                case 55:
                    Dz55.setSelected(true);
                    this.Dz55ActionPerformed(evt);
                    break;
                case 56:
                    Dz56.setSelected(true);
                    this.Dz56ActionPerformed(evt);
                    break;
                case 57:
                    Dz57.setSelected(true);
                    this.Dz57ActionPerformed(evt);
                    break;
                case 58:
                    Dz58.setSelected(true);
                    this.Dz58ActionPerformed(evt);
                    break;
                case 59:
                    Dz59.setSelected(true);
                    this.Dz59ActionPerformed(evt);
                    break;
                case 60:
                    Dz60.setSelected(true);
                    this.Dz60ActionPerformed(evt);
                    break;
            }
                    
                
        }
        
    }//GEN-LAST:event_RandomActionPerformed

    private void Dz01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz01ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz01.isSelected()) {
            
                jogo.add(1);
            
        } else {
            int n = jogo.lastIndexOf(1);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);


    }//GEN-LAST:event_Dz01ActionPerformed

    private void Dz02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz02ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz02.isSelected()) {
            
                jogo.add(2);
            
        } else {
            int n = jogo.lastIndexOf(2);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz02ActionPerformed

    private void Dz03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz03ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz03.isSelected()) {
           
                jogo.add(3);
            
        } else {
            int n = jogo.lastIndexOf(3);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz03ActionPerformed

    private void Dz04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz04ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz04.isSelected()) {
            
                jogo.add(4);
            
        } else {
            int n = jogo.lastIndexOf(4);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz04ActionPerformed

    private void Dz05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz05ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz05.isSelected()) {
            
                jogo.add(5);
            
        } else {
            int n = jogo.lastIndexOf(5);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz05ActionPerformed

    private void Dz06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz06ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz06.isSelected()) {
            
                jogo.add(6);
            
        } else {
            int n = jogo.lastIndexOf(6);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz06ActionPerformed

    private void Dz07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz07ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz07.isSelected()) {
            
                jogo.add(7);
            
        } else {
            int n = jogo.lastIndexOf(7);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz07ActionPerformed

    private void Dz08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz08ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz08.isSelected()) {
            
                jogo.add(8);
            
        } else {
            int n = jogo.lastIndexOf(8);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz08ActionPerformed

    private void Dz09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz09ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz09.isSelected()) {
            
                jogo.add(9);
            
        } else {
            int n = jogo.lastIndexOf(9);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz09ActionPerformed

    private void Dz10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz10ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz10.isSelected()) {
            
                jogo.add(10);
            
        } else {
            int n = jogo.lastIndexOf(10);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz10ActionPerformed

    private void Dz11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz11ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz11.isSelected()) {
            
                jogo.add(11);
            
        } else {
            int n = jogo.lastIndexOf(11);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);

    }//GEN-LAST:event_Dz11ActionPerformed

    private void Dz12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz12ActionPerformed
       jogoText = "";
        int tam = jogo.size();

        if (Dz12.isSelected()) {
            
                jogo.add(12);
            
        } else {
            int n = jogo.lastIndexOf(12);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz12ActionPerformed

    private void Dz13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz13ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz13.isSelected()) {
            
                jogo.add(13);
            
        } else {
            int n = jogo.lastIndexOf(13);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz13ActionPerformed

    private void Dz14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz14ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz14.isSelected()) {
            
                jogo.add(14);
            
        } else {
            int n = jogo.lastIndexOf(14);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz14ActionPerformed

    private void Dz15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz15ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz15.isSelected()) {
            
                jogo.add(15);
            
        } else {
            int n = jogo.lastIndexOf(15);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz15ActionPerformed

    private void Dz16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz16ActionPerformed
       jogoText = "";
        int tam = jogo.size();

        if (Dz16.isSelected()) {
            
                jogo.add(16);
            
        } else {
            int n = jogo.lastIndexOf(16);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz16ActionPerformed

    private void Dz17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz17ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz17.isSelected()) {
            
                jogo.add(17);
            
        } else {
            int n = jogo.lastIndexOf(17);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz17ActionPerformed

    private void Dz18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz18ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz18.isSelected()) {
            
                jogo.add(18);
            
        } else {
            int n = jogo.lastIndexOf(18);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz18ActionPerformed

    private void Dz19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz19ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz19.isSelected()) {
            
                jogo.add(19);
            
        } else {
            int n = jogo.lastIndexOf(19);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz19ActionPerformed

    private void Dz20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz20ActionPerformed
        jogoText = "";
        int tam = jogo.size();

        if (Dz20.isSelected()) {
            
                jogo.add(20);
            
        } else {
            int n = jogo.lastIndexOf(20);
            jogo.remove(n);
        }

        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz20ActionPerformed

    private void Dz21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz21ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz21.isSelected()) {
                jogo.add(21);
            }
            else {
                int n = jogo.lastIndexOf(21);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz21ActionPerformed

    private void Dz22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz22ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz22.isSelected()) {
                jogo.add(22);
            }
            else {
                int n = jogo.lastIndexOf(22);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz22ActionPerformed

    private void Dz23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz23ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz23.isSelected()) {
                jogo.add(23);
            }
            else {
                int n = jogo.lastIndexOf(23);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz23ActionPerformed

    private void Dz24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz24ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz24.isSelected()) {
                jogo.add(24);
            }
            else {
                int n = jogo.lastIndexOf(24);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz24ActionPerformed

    private void Dz25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz25ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz25.isSelected()) {
                jogo.add(25);
            }
            else {
                int n = jogo.lastIndexOf(25);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz25ActionPerformed

    private void Dz26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz26ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz26.isSelected()) {
                jogo.add(26);
            }
            else {
                int n = jogo.lastIndexOf(26);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz26ActionPerformed

    private void Dz27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz27ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz27.isSelected()) {
                jogo.add(27);
            }
            else {
                int n = jogo.lastIndexOf(27);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz27ActionPerformed

    private void Dz28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz28ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz28.isSelected()) {
                jogo.add(28);
            }
            else {
                int n = jogo.lastIndexOf(28);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz28ActionPerformed

    private void Dz29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz29ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz29.isSelected()) {
                jogo.add(29);
            }
            else {
                int n = jogo.lastIndexOf(29);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz29ActionPerformed

    private void Dz30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz30ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz30.isSelected()) {
                jogo.add(30);
            }
            else {
                int n = jogo.lastIndexOf(30);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz30ActionPerformed

    private void Dz31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz31ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz31.isSelected()) {
                jogo.add(31);
            }
            else {
                int n = jogo.lastIndexOf(31);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz31ActionPerformed

    private void Dz32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz32ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz32.isSelected()) {
                jogo.add(32);
            }
            else {
                int n = jogo.lastIndexOf(32);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz32ActionPerformed

    private void Dz33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz33ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz33.isSelected()) {
                jogo.add(33);
            }
            else {
                int n = jogo.lastIndexOf(33);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz33ActionPerformed

    private void Dz34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz34ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz34.isSelected()) {
                jogo.add(34);
            }
            else {
                int n = jogo.lastIndexOf(34);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz34ActionPerformed

    private void Dz35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz35ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz35.isSelected()) {
                jogo.add(35);
            }
            else {
                int n = jogo.lastIndexOf(35);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz35ActionPerformed

    private void Dz36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz36ActionPerformed
       jogoText = "";
        int tam = jogo.size();
       
            if (Dz36.isSelected()) {
                jogo.add(36);
            }
            else {
                int n = jogo.lastIndexOf(36);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz36ActionPerformed

    private void Dz37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz37ActionPerformed
       jogoText = "";
        int tam = jogo.size();
        
            if (Dz37.isSelected()) {
                jogo.add(37);
            }
            else {
                int n = jogo.lastIndexOf(37);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz37ActionPerformed

    private void Dz38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz38ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz38.isSelected()) {
                jogo.add(38);
            }
            else {
                int n = jogo.lastIndexOf(38);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz38ActionPerformed

    private void Dz39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz39ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz39.isSelected()) {
                jogo.add(39);
            }
            else {
                int n = jogo.lastIndexOf(39);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz39ActionPerformed

    private void Dz40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz40ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz40.isSelected()) {
                jogo.add(40);
            }
            else {
                int n = jogo.lastIndexOf(40);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz40ActionPerformed

    private void Dz41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz41ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz41.isSelected()) {
                jogo.add(41);
            }
            else {
                int n = jogo.lastIndexOf(41);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz41ActionPerformed

    private void Dz42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz42ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz42.isSelected()) {
                jogo.add(42);
            }
            else {
                int n = jogo.lastIndexOf(42);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz42ActionPerformed

    private void Dz43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz43ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz43.isSelected()) {
                jogo.add(43);
            }
            else {
                int n = jogo.lastIndexOf(43);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz43ActionPerformed

    private void Dz44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz44ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz44.isSelected()) {
                jogo.add(44);
            }
            else {
                int n = jogo.lastIndexOf(44);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz44ActionPerformed

    private void Dz45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz45ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz45.isSelected()) {
                jogo.add(45);
            }
            else {
                int n = jogo.lastIndexOf(45);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz45ActionPerformed

    private void Dz46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz46ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz46.isSelected()) {
                jogo.add(46);
            }
            else {
                int n = jogo.lastIndexOf(46);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz46ActionPerformed

    private void Dz47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz47ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz47.isSelected()) {
                jogo.add(47);
            }
            else {
                int n = jogo.lastIndexOf(47);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz47ActionPerformed

    private void Dz48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz48ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz48.isSelected()) {
                jogo.add(48);
            }
            else {
                int n = jogo.lastIndexOf(48);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz48ActionPerformed

    private void Dz49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz49ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz49.isSelected()) {
                jogo.add(49);
            }
            else {
                int n = jogo.lastIndexOf(49);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz49ActionPerformed

    private void Dz50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz50ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz50.isSelected()) {
                jogo.add(50);
            }
            else {
                int n = jogo.lastIndexOf(50);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz50ActionPerformed

    private void Dz51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz51ActionPerformed
       jogoText = "";
        int tam = jogo.size();
        
            if (Dz51.isSelected()) {
                jogo.add(51);
            }
            else {
                int n = jogo.lastIndexOf(51);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz51ActionPerformed

    private void Dz52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz52ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz52.isSelected()) {
                jogo.add(52);
            }
            else {
                int n = jogo.lastIndexOf(52);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz52ActionPerformed

    private void Dz53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz53ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz53.isSelected()) {
                jogo.add(53);
            }
            else {
                int n = jogo.lastIndexOf(53);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz53ActionPerformed

    private void Dz54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz54ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz54.isSelected()) {
                jogo.add(54);
            }
            else {
                int n = jogo.lastIndexOf(54);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz54ActionPerformed

    private void Dz55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz55ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz55.isSelected()) {
                jogo.add(55);
            }
            else {
                int n = jogo.lastIndexOf(55);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz55ActionPerformed

    private void Dz56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz56ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz56.isSelected()) {
                jogo.add(56);
            }
            else {
                int n = jogo.lastIndexOf(56);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz56ActionPerformed

    private void Dz57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz57ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz57.isSelected()) {
                jogo.add(57);
            }
            else {
                int n = jogo.lastIndexOf(57);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz57ActionPerformed

    private void Dz58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz58ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz58.isSelected()) {
                jogo.add(58);
            }
            else {
                int n = jogo.lastIndexOf(58);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz58ActionPerformed

    private void Dz59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz59ActionPerformed
        jogoText = "";
        int tam = jogo.size();
        
            if (Dz59.isSelected()) {
                jogo.add(59);
            }
            else {
                int n = jogo.lastIndexOf(59);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz59ActionPerformed

    private void Dz60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dz60ActionPerformed
       jogoText = "";
        int tam = jogo.size();
        
            if (Dz60.isSelected()) {
                jogo.add(60);
            }
            else {
                int n = jogo.lastIndexOf(60);
                jogo.remove(n);
                System.out.println(jogo.size());
            }
        
        for (int element : jogo) {
            jogoText += Integer.toString(element) + "  ";
        }
        aposta.setText(jogoText);
    }//GEN-LAST:event_Dz60ActionPerformed

    private void salvarApostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarApostaActionPerformed
        
        int jogoTam = jogo.size();
        if  (jogoTam == Quantidade){
            int numFeito = this.numCartela + 1;
            Quantidade = 6;

            String num = Integer.toString(numFeito);
            CartelaNum.setText(num);

            jogoMega jogoFeito = new jogoMega();
            jogoFeito.jogo = jogo;
            jogoFeito.numCartela = numFeito;

            todosJogos.add(jogoFeito);

            Cartela nova = new Cartela();
            nova.numCartela = this.numCartela + 1;
            nova.CartelaNum.setText(Integer.toString(numFeito));
            this.setVisible(false);
            nova.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null,"Favor Inserir a quantidade informada");
        }
        
    }//GEN-LAST:event_salvarApostaActionPerformed

    private void SorteioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SorteioActionPerformed

        Sorteio sort = new Sorteio();
        String numeros = "";
        int[] jogoSort = new int[10];
        
        for (jogoMega jogo : todosJogos){
            
            for (int numero : jogo.jogo){
                numeros += Integer.toString(numero) + " ";
            }
            
            sort.JogosSalvos.append(Integer.toString(jogo.numCartela)+ " - " + numeros + "\n");
            numeros = "";
        }
        
        int[] resultado = sorteaSena();
        Arrays.sort(resultado);
        String lgResult = "";
        for (int num : resultado){
            lgResult += Integer.toString(num) + " ";
        }
        sort.result.setText(lgResult);
        
        for (jogoMega jogo : todosJogos){
            int i = 0;
            int acertos = 0;
            for (int num : jogo.jogo){
                jogoSort[i] = num;
                i++;
            }
            Arrays.sort(jogoSort);
            
            for (int num : resultado){
                int pesquisa = Arrays.binarySearch(jogoSort, num);
                if (pesquisa >= 0){
                    acertos++;
                }
            }
        
            
            sort.Resultado2.append(Integer.toString(jogo.numCartela)+ " - " + acertos + " acertos\n");
            numeros = "";
        }
        
        
        
        
        todosJogos.clear();
        sort.setVisible(true);
        
    }//GEN-LAST:event_SorteioActionPerformed

    private void Qnt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qnt6ActionPerformed
        Quantidade = 6;
    }//GEN-LAST:event_Qnt6ActionPerformed

    private void Qnt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qnt7ActionPerformed
        Quantidade = 7;
    }//GEN-LAST:event_Qnt7ActionPerformed

    private void Qnt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qnt8ActionPerformed
        Quantidade = 8;
    }//GEN-LAST:event_Qnt8ActionPerformed

    private void Qnt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qnt9ActionPerformed
        Quantidade = 9;
    }//GEN-LAST:event_Qnt9ActionPerformed

    private void Qnt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Qnt10ActionPerformed
        Quantidade = 10;
    }//GEN-LAST:event_Qnt10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CartelaNum;
    private javax.swing.JCheckBox Dz01;
    private javax.swing.JCheckBox Dz02;
    private javax.swing.JCheckBox Dz03;
    private javax.swing.JCheckBox Dz04;
    private javax.swing.JCheckBox Dz05;
    private javax.swing.JCheckBox Dz06;
    private javax.swing.JCheckBox Dz07;
    private javax.swing.JCheckBox Dz08;
    private javax.swing.JCheckBox Dz09;
    private javax.swing.JCheckBox Dz10;
    private javax.swing.JCheckBox Dz11;
    private javax.swing.JCheckBox Dz12;
    private javax.swing.JCheckBox Dz13;
    private javax.swing.JCheckBox Dz14;
    private javax.swing.JCheckBox Dz15;
    private javax.swing.JCheckBox Dz16;
    private javax.swing.JCheckBox Dz17;
    private javax.swing.JCheckBox Dz18;
    private javax.swing.JCheckBox Dz19;
    private javax.swing.JCheckBox Dz20;
    private javax.swing.JCheckBox Dz21;
    private javax.swing.JCheckBox Dz22;
    private javax.swing.JCheckBox Dz23;
    private javax.swing.JCheckBox Dz24;
    private javax.swing.JCheckBox Dz25;
    private javax.swing.JCheckBox Dz26;
    private javax.swing.JCheckBox Dz27;
    private javax.swing.JCheckBox Dz28;
    private javax.swing.JCheckBox Dz29;
    private javax.swing.JCheckBox Dz30;
    private javax.swing.JCheckBox Dz31;
    private javax.swing.JCheckBox Dz32;
    private javax.swing.JCheckBox Dz33;
    private javax.swing.JCheckBox Dz34;
    private javax.swing.JCheckBox Dz35;
    private javax.swing.JCheckBox Dz36;
    private javax.swing.JCheckBox Dz37;
    private javax.swing.JCheckBox Dz38;
    private javax.swing.JCheckBox Dz39;
    private javax.swing.JCheckBox Dz40;
    private javax.swing.JCheckBox Dz41;
    private javax.swing.JCheckBox Dz42;
    private javax.swing.JCheckBox Dz43;
    private javax.swing.JCheckBox Dz44;
    private javax.swing.JCheckBox Dz45;
    private javax.swing.JCheckBox Dz46;
    private javax.swing.JCheckBox Dz47;
    private javax.swing.JCheckBox Dz48;
    private javax.swing.JCheckBox Dz49;
    private javax.swing.JCheckBox Dz50;
    private javax.swing.JCheckBox Dz51;
    private javax.swing.JCheckBox Dz52;
    private javax.swing.JCheckBox Dz53;
    private javax.swing.JCheckBox Dz54;
    private javax.swing.JCheckBox Dz55;
    private javax.swing.JCheckBox Dz56;
    private javax.swing.JCheckBox Dz57;
    private javax.swing.JCheckBox Dz58;
    private javax.swing.JCheckBox Dz59;
    private javax.swing.JCheckBox Dz60;
    private javax.swing.JRadioButton Qnt10;
    private javax.swing.JRadioButton Qnt6;
    private javax.swing.JRadioButton Qnt7;
    private javax.swing.JRadioButton Qnt8;
    private javax.swing.JRadioButton Qnt9;
    private javax.swing.JButton Random;
    private javax.swing.JButton Sorteio;
    private javax.swing.JLabel aposta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton salvarAposta;
    // End of variables declaration//GEN-END:variables
}
